INPUT_FOLDER = "/var/www/input"
PROCESSED_INPUT_FOLDER = "/var/www/input_processed"
OUTPUT_FOLDER = "/var/www/output"
ERROR_FOLDER = "/var/www/error"
CONFIG_FILE = "/var/www/config.json"
TAG_DEFAULT_VALUES_FILE = "/var/www/tag_default_values.json"
TMP_FOLDER = "/var/www/tmp"
